apiVersion: v1
kind: Secret
metadata:
  name: dockerconfigjson
  namespace: cinemaabyss
data:
  .dockerconfigjson: ewoJImF1dGhzIjogewoJCSIxNzIuMTYuMTIuNTE6ODA4MiI6IHt9LAoJCSIxNzIuMTYuMTIuOTA6ODA4MiI6IHt9LAoJCSJsb2NhbGhvc3Q6ODA4MiI6IHt9LAoJCSJnaGNyLmlvIjogewogICAgICAgICAgICAgICAgICAgICAgICJhdXRoIjogImFYWmhiaTEyWlhJNloyaHdYMVIyYld3NWNWZHdjakpXVG1vMFptWnllbEExVlU1NFozQlFWMHhSTURBeWFuQm1SZz09IgogICAgICAgICAgICAgICAgfQoJfSwKCSJjcmVkc1N0b3JlIjogImRlc2t0b3AiLAoJImN1cnJlbnRDb250ZXh0IjogImRlZmF1bHQiLAoJInBsdWdpbnMiOiB7CgkJIi14LWNsaS1oaW50cyI6IHsKCQkJImVuYWJsZWQiOiAidHJ1ZSIKCQl9Cgl9Cn0=
type: kubernetes.io/dockerconfigjson
