apiVersion: v1
kind: Secret
metadata:
  name: dockerconfigjson
  namespace: cinemaabyss
data:
  .dockerconfigjson: ewoJImF1dGhzIjogewoJCSJnaGNyLmlvIjogewoJCQkiYXV0aCI6ICJhWFpoYm1OdmRtRmxPbWRvY0Y5NVpsWlljSGh3Y1dkRFNUWTVZVzFNZWxodWRGSkVhRXMwWm10dWN6WXdibFF3VWtrPSIKCSAJfQoJfSwKCSJjcmVkc1N0b3JlIjogImRlc2t0b3AiLAoJImN1cnJlbnRDb250ZXh0IjogImRlc2t0b3AtbGludXgiLAoJInBsdWdpbnMiOiB7CgkJImRlYnVnIjogewoJCQkiaG9va3MiOiAiZXhlYyIKCQl9LAoJCSJzY291dCI6IHsKCQkJImhvb2tzIjogInB1bGwsYnVpbGR4IGJ1aWxkIgoJCX0KCX0sCgkiZmVhdHVyZXMiOiB7CgkJImhvb2tzIjogInRydWUiCgl9Cn0=
type: kubernetes.io/dockerconfigjson


